<?php
/**
 * Dynamic CSS functions
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

/**
 * Get dynamic CSS
 */
function uncode_get_page_dynamic_css() {
	global $uncode_post_data, $uncode_dynamic_css_selectors, $row_sticky_columns;

	$uncode_dynamic_css_selectors = array();

	// Get an array that contains all the raw content attached to the page
	$content_array = uncode_get_post_data_content_array();

	// Generate custom CSS for the custom colors
	$dynamic_css = uncode_get_dynamic_colors_css( $content_array );

	// Generate custom CSS for the sticky scroll indexes
	$dynamic_css .= uncode_get_dynamic_sticky_scroll_css( $content_array );

	// Generate custom CSS for css grids
	$dynamic_css .= uncode_get_dynamic_css_grid_css( $content_array );

	// Generate custom CSS font size
	$dynamic_css .= uncode_get_dynamic_css_font_size( $content_array );

	// Generate custom CSS menu block
	$dynamic_css .= uncode_get_dynamic_css_menu_block( $content_array );

	// Generate custom CSS text indent
	$dynamic_css .= uncode_get_dynamic_css_text_indent( $content_array );

	// Generate custom CSS nav_carousel
	$dynamic_css .= uncode_get_dynamic_css_nav_carousel( $content_array );

	// Generate custom CSS for linear grids
	$dynamic_css .= uncode_get_dynamic_linear_grid_css( $content_array );

	return $dynamic_css;
}

/**
 * Get dynamic CSS generated by custom colors
 */
function uncode_get_dynamic_colors_css( $content_array ) {
	$css = '';

	foreach ( $content_array as $content ) {
		if ( strpos( $content, 'uncode-gradient' ) !== false || strpos( $content, 'uncode-solid' ) !== false ) {
			$css .= uncode_get_single_dynamic_colors_css( $content );
		}
	}

	return $css;
}

/**
 * Get dynamic colors CSS from a piece of content
 */
function uncode_get_single_dynamic_colors_css( $content ) {
	$css = '';

	$regex = '/\[([^\[]+) [^\s]+_type=\"(uncode-solid|uncode-gradient)\".*?\]/m';
	preg_match_all( $regex, $content, $shortcodes, PREG_SET_ORDER, 0 );

	$shortcodes_with_colors = uncode_get_shortcodes_with_colors( $shortcodes );

	foreach ( $shortcodes_with_colors as $shortcode ) {
		$shortcode_data = uncode_get_shortcodes_with_colors_data( $shortcode );

		if ( count( $shortcode_data ) > 0 ) {
			$css .= uncode_get_dynamic_colors_css_from_shortcode( $shortcode_data );
		}
	}

	return $css;
}

/**
 * Get shortcodes that have a custom color
 */
function uncode_get_shortcodes_with_colors( $shortcodes ) {
	$shortcodes_with_colors = array();

	foreach ( $shortcodes as $key => $value ) {
		if ( isset( $value[0] ) && $value[0] && isset( $value[2] ) && $value[2] ) {
			$shortcodes_with_colors[] = $value[0];
		}
	}

	return $shortcodes_with_colors;
}

/**
 * Get data of each shortcode that has a custom color
 */
function uncode_get_shortcodes_with_colors_data( $shortcode ) {
	$regex_id = '/\[(.+?\s+)/';
	preg_match_all( $regex_id, $shortcode, $shortcode_id, PREG_SET_ORDER, 0 );

	$shortcode_data = array(
		'type'       => '',
		'id'         => '',
		'attributes' => array(),
	);

	if ( isset( $shortcode_id[0] ) && $shortcode_id[0] && isset( $shortcode_id[0][1] ) && $shortcode_id[0][1] ) {
		$shortcode_id = trim( $shortcode_id[0][1] );

		if ( $shortcode_id ) {
			$regex_attr = '/ (.*?)=\"(.*?)\"/';
			preg_match_all( $regex_attr, $shortcode, $attributes, PREG_SET_ORDER, 0 );

			$shortcode_data['type'] = $shortcode_id;

			foreach ( $attributes as $attribute ) {
				if ( isset( $attribute[1] ) && $attribute[1] && isset( $attribute[2] ) && $attribute[2] ) {
					if ( $attribute[1] === 'uncode_shortcode_id' ) {
						$shortcode_data['id'] = absint( $attribute[2] );
					} else {
						$shortcode_data['attributes'][$attribute[1]] = $attribute[2];
					}
				}
			}
		}
	}

	if ( $shortcode_data['id'] > 0 ) {
		return $shortcode_data;
	}

	return array();
}

/**
 * Get CSS from custom color shortcode
 */
function uncode_get_dynamic_colors_css_from_shortcode( $shortcode ) {
	global $uncode_dynamic_css_selectors;

	$css = '';

	if ( isset( $shortcode['type'] ) && isset( $shortcode['id'] ) && isset( $shortcode['attributes'] ) && is_array( $shortcode['attributes'] ) ) {
		// Return early if we don't support this module
		if ( ! in_array( $shortcode['type'], uncode_get_modules_with_dynamic_colors() ) ) {
			return $css;
		}

		$shortcode_id = absint( $shortcode['id'] );

		// Check if we have already processed the same ID
		// (ie. a cloned module)
		if ( is_array( $uncode_dynamic_css_selectors ) && in_array( $shortcode_id, $uncode_dynamic_css_selectors ) ) {
			return $css;
		}

		$custom_color_keys = array();

		foreach ( $shortcode['attributes'] as $attributes_key => $attributes_value ) {
			if ( $attributes_value === 'uncode-solid' || $attributes_value === 'uncode-gradient' ) {
				$custom_color_keys[] = str_replace( '_type', '', $attributes_key );
			}
			if ( $attributes_key === 'text_stroke' && $attributes_value === 'yes' ) {
				$custom_color_keys[] = 'text_stroke';
			}

		}

		$shortcode_function_name = 'uncode_get_dynamic_colors_css_for_shortcode_' . str_replace( '-', '_', $shortcode['type'] );

		if ( function_exists( $shortcode_function_name ) ) {
			$css .= call_user_func_array( $shortcode_function_name, array( $shortcode, $custom_color_keys ) );
		}

		$uncode_dynamic_css_selectors[] = $shortcode['id'];
	}

	return $css;
}

/**
 * List of modules with dynamic colors
 */
function uncode_get_modules_with_dynamic_colors() {
	$modules = array(
		'uncode_menu_block',
		'uncode_author_profile',
		'vc_button',
		'vc_column',
		'vc_column_inner',
		'uncode_consent_notice',
		'vc_accordion',
		'vc_custom_heading',
		'vc_icon',
		'vc_gallery',
		'vc_message',
		'vc_row',
		'vc_row_inner',
		'vc_section',
		'vc_single_image',
		'vc_column_text',
		'vc_separator',
		'vc_gmaps',
		'vc_pie',
		'vc_tabs',
		'uncode_pricing',
		'uncode_pricing_list',
		'uncode_star_rating',
		'uncode_list',
		'uncode_index',
		'vc_gallery',
		'vc_single_image',
		'uncode_counter',
		'uncode_vertical_text',
		'uncode_woocommerce_cart',
		'uncode_woocommerce_checkout',
		'uncode_woocommerce_my_account',
		'uncode_custom_fields'
	);

	return $modules;
}

/**
 * Get dynamic CSS generated by sticky scroll
 */
function uncode_get_dynamic_sticky_scroll_css( $content_array ) {
	$menutype = ot_get_option('_uncode_headers');

	$css = '';

	foreach ( $content_array as $content ) {
		if ( strpos( $content, 'index_type="sticky-scroll"' ) !== false ) {
			$css .= uncode_get_single_dynamic_sticky_scroll_css( $content );
		}
	}

	return $css;
}

/**
 * Get dynamic sticky scroll CSS from a piece of content
 */
function uncode_get_single_dynamic_sticky_scroll_css( $content ) {
	$css = '';

	$regex_index_vw = '/\[[uncode_index|vc_gallery]([^\]]+)type=\"sticky-scroll\".*?\]/m';
	preg_match_all( $regex_index_vw, $content, $indexes_vw, PREG_SET_ORDER, 0 );

	foreach ( $indexes_vw as $index_vw ) {

		$params = $index_vw[0];
		preg_match('/ uncode_shortcode_id=\"(.*?)"/', $params, $id); //row ID
		preg_match('/ sticky_th_grid_lg=\"(.*?)"/', $params, $lg);
		preg_match('/ sticky_th_grid_md=\"(.*?)"/', $params, $md);
		preg_match('/ no_sticky_scroll_tablet=\"(.*?)"/', $params, $no_md);
		preg_match('/ sticky_th_grid_sm=\"(.*?)"/', $params, $sm);
		preg_match('/ no_sticky_scroll_mobile=\"(.*?)"/', $params, $no_sm);

		$shortcode_data = array(
			'size' => 'vw',
			'id' => $id[1],
			'lg' => isset($lg[1]) ? $lg[1] : 3,
			'md' => isset($no_md[1]) ? 1 : (isset($md[1]) ? $md[1] : 3),
			'sm' => isset($no_sm[1]) ? 1 : (isset($sm[1]) ? $sm[1] : 1),
		);
		$css .= uncode_get_dynamic_sticky_scroll_css_from_shortcode( $shortcode_data );

	}

	return $css;
}

/**
 * Get CSS from sticky scroll shortcode
 */
function uncode_get_dynamic_sticky_scroll_css_from_shortcode( $shortcode_data ) {
	global $uncode_dynamic_css_selectors, $row_sticky_columns;

	$css = '';

	if ( isset( $shortcode_data['id'] ) && isset( $shortcode_data['lg'] ) ) {

		$shortcode_id = absint( $shortcode_data['id'] );

		// Check if we have already processed the same ID
		// (ie. a cloned module)
		if ( is_array( $uncode_dynamic_css_selectors ) && in_array( 'hor-scroll-'.$shortcode_id, $uncode_dynamic_css_selectors ) ) {
			return $css;
		}

		if ( function_exists( 'uncode_get_sticky_scroll_css_for_shortcode_index' ) ) {
			$css .= uncode_get_sticky_scroll_css_for_shortcode_index( $shortcode_data );
		}

		$uncode_dynamic_css_selectors[] = 'hor-scroll-'.$shortcode_data['id'];
	}

	return $css;
}

/**
 * Get dynamic CSS generated by linear grids
 */
function uncode_get_dynamic_linear_grid_css( $content_array ) {
	$css = '';

	foreach ( $content_array as $content ) {
		if ( strpos( $content, 'type="linear"' ) !== false ) {
			$css .= uncode_get_single_dynamic_linear_grid_css( $content );
		}
	}

	return $css;
}

/**
 * Get dynamic linear grids CSS from a piece of content
 */
function uncode_get_single_dynamic_linear_grid_css( $content ) {
	$css = '';

	$regex_index = '/\[[uncode_index|vc_gallery]([^\]]+)type=\"linear\".*?\]/m';
	preg_match_all( $regex_index, $content, $indexes, PREG_SET_ORDER, 0 );

	foreach ( $indexes as $index ) {
		$params = $index[0];

		preg_match('/ uncode_shortcode_id=\"(.*?)"/', $params, $id); //row ID
		preg_match('/ size_by=\"(.*?)"/', $params, $by);
		preg_match('/ linear_width=\"(.*?)"/', $params, $width);
		preg_match('/ linear_height=\"(.*?)"/', $params, $height);
		preg_match('/ single_text=\"(.*?)"/', $params, $layout);
		preg_match('/ single_image_size=\"(.*?)"/', $params, $size);

		$shortcode_data = array(
			'id'		=> $id[1],
			'by'		=> isset( $by[1] ) ? $by[1] : '',
			'w'			=> isset( $width[1] ) ? $width[1] : '',
			'h'			=> isset( $height[1] ) ? $height[1] : '',
			'layout'	=> isset( $layout[1] ) ? $layout[1] : '',
			'size'		=> isset( $size[1] ) ? $size[1] : ''
		);
		$css .= uncode_get_dynamic_linear_grids_css_from_shortcode( $shortcode_data );
	}

	return $css;
}

/**
 * Get CSS from custom grids shortcode
 */
function uncode_get_dynamic_linear_grids_css_from_shortcode( $shortcode_data ) {
	global $uncode_dynamic_css_selectors;

	$css = '';

	if ( isset( $shortcode_data['id'] ) && ( isset( $shortcode_data['w'] ) || isset( $shortcode_data['h'] ) ) ) {

		$shortcode_id = absint( $shortcode_data['id'] );

		// Check if we have already processed the same ID
		// (ie. a cloned module)
		if ( is_array( $uncode_dynamic_css_selectors ) && in_array( 'lineargrid-'.$shortcode_id, $uncode_dynamic_css_selectors ) ) {
			return $css;
		}

		if ( function_exists( 'uncode_get_linear_grids_css_for_shortcode_vc_gallery' ) ) {
			$css .= uncode_get_linear_grids_css_for_shortcode_vc_gallery( $shortcode_data );
		}

		$uncode_dynamic_css_selectors[] = 'lineargrid-'.$shortcode_data['id'];
	}

	return $css;
}

/**
 * Get dynamic CSS generated by css grids
 */
function uncode_get_dynamic_css_grid_css( $content_array ) {
	$css = '';

	foreach ( $content_array as $content ) {
		if ( strpos( $content, 'type="css_grid"' ) !== false ) {
			$css .= uncode_get_single_dynamic_css_grid_css( $content );
		}
	}

	return $css;
}

/**
 * Get dynamic css grids CSS from a piece of content
 */
function uncode_get_single_dynamic_css_grid_css( $content ) {
	$css = '';

	$regex_index = '/\[[uncode_index|vc_gallery]([^\]]+)type=\"css_grid\".*?\]/m';
	preg_match_all( $regex_index, $content, $indexes, PREG_SET_ORDER, 0 );

	foreach ( $indexes as $index ) {
		$params = $index[0];

		preg_match('/ uncode_shortcode_id=\"(.*?)"/', $params, $id); //row ID
		preg_match('/ grid_items=\"(.*?)"/', $params, $items);
		preg_match('/ screen_lg_breakpoint=\"(.*?)"/', $params, $lg);
		preg_match('/ screen_lg_items=\"(.*?)"/', $params, $lg_items);
		preg_match('/ screen_md_breakpoint=\"(.*?)"/', $params, $md);
		preg_match('/ screen_md_items=\"(.*?)"/', $params, $md_items);
		preg_match('/ screen_sm_breakpoint=\"(.*?)"/', $params, $sm);
		preg_match('/ screen_sm_items=\"(.*?)"/', $params, $sm_items);

		$shortcode_data = array(
			'id'       => $id[1],
			'items'    => isset( $items[1] ) ? $items[1] : 4,
			'lg'       => isset( $lg[1] ) ? $lg[1] : 1000,
			'lg_items' => isset( $lg_items[1] ) ? $lg_items[1] : 3,
			'md'       => isset( $md[1] ) ? $md[1] : 600,
			'md_items' => isset( $md_items[1] ) ? $md_items[1] : 2,
			'sm'       => isset( $sm[1] ) ? $sm[1] : 480,
			'sm_items' => isset( $sm_items[1] ) ? $sm_items[1] : 1,
		);
		$css .= uncode_get_dynamic_css_grids_css_from_shortcode( $shortcode_data );
	}

	return $css;
}

/**
 * Get CSS from custom grids shortcode
 */
function uncode_get_dynamic_css_grids_css_from_shortcode( $shortcode_data ) {
	global $uncode_dynamic_css_selectors;

	$css = '';

	if ( isset( $shortcode_data['id'] ) && isset( $shortcode_data['lg'] ) ) {

		$shortcode_id = absint( $shortcode_data['id'] );

		// Check if we have already processed the same ID
		// (ie. a cloned module)
		if ( is_array( $uncode_dynamic_css_selectors ) && in_array( 'cssgrid-'.$shortcode_id, $uncode_dynamic_css_selectors ) ) {
			return $css;
		}

		if ( function_exists( 'uncode_get_css_grids_css_for_shortcode_index' ) ) {
			$css .= uncode_get_css_grids_css_for_shortcode_index( $shortcode_data );
		}

		$uncode_dynamic_css_selectors[] = 'cssgrid-'.$shortcode_data['id'];
	}

	return $css;
}

/**
 * Get dynamic font size CSS
 */
function uncode_get_dynamic_css_font_size( $content_array ) {
	$css = '';

	foreach ( $content_array as $content ) {
		if ( strpos( $content, 'custom_size="' ) !== false ) {
			$css .= uncode_get_single_dynamic_css_font_size( $content );
		}
	}

	return $css;
}

/**
 * Get dynamic font size CSS from a piece of content
 */
function uncode_get_single_dynamic_css_font_size( $content ) {
	$css = '';

	$regex_index = '/\[(\w+)([^\[]*?)heading_custom_size="(.*?)"(.*?)\]/m';
	preg_match_all( $regex_index, $content, $indexes, PREG_SET_ORDER, 0 );

	foreach ( $indexes as $index ) {
		$params = $index[0];

		preg_match('/ uncode_shortcode_id=\"(.*?)"/', $params, $id); //row ID
		preg_match('/ heading_custom_size=\"(.*?)"/', $params, $size);

		$shortcode_data = array(
			'id'        => $id[1],
			'font_size' => $size[1],
		);
		$css .= uncode_get_dynamic_css_font_size_shortcode( $shortcode_data );
	}

	$regex_index_2 = '/\[(uncode_star_rating|uncode_custom_fields)([^\[]*?)custom_size="(.*?)"(.*?)\]/m';
	preg_match_all( $regex_index_2, $content, $indexes_2, PREG_SET_ORDER, 0 );

	foreach ( $indexes_2 as $index_2 ) {
		$params = $index_2[0];

		preg_match('/ uncode_shortcode_id=\"(.*?)"/', $params, $id); //row ID
		preg_match('/ custom_size=\"(.*?)"/', $params, $size);

		$shortcode_data = array(
			'id'        => $id[1],
			'font_size' => $size[1],
		);
		$css .= uncode_get_dynamic_css_font_size_shortcode( $shortcode_data );
	}

	$regex_index_3 = '/\[(\w+)([^\[]*?)title_custom_size="(.*?)"(.*?)\]/m';
	preg_match_all( $regex_index_3, $content, $indexes_3, PREG_SET_ORDER, 0 );

	foreach ( $indexes_3 as $index_3 ) {
		$params = $index_3[0];

		preg_match('/ uncode_shortcode_id=\"(.*?)"/', $params, $id); //row ID
		preg_match('/ title_custom_size=\"(.*?)"/', $params, $size);

		$shortcode_data = array(
			'id'        => 'title-' . $id[1],
			'font_size' => $size[1],
		);
		$css .= uncode_get_dynamic_css_font_size_shortcode( $shortcode_data );
	}

	$regex_index_4 = '/\[(\w+)([^\[]*?)sec_custom_size="(.*?)"(.*?)\]/m';
	preg_match_all( $regex_index_4, $content, $indexes_4, PREG_SET_ORDER, 0 );

	foreach ( $indexes_4 as $index_4 ) {
		$params = $index_4[0];

		preg_match('/ uncode_shortcode_id=\"(.*?)"/', $params, $id); //row ID
		preg_match('/ sec_custom_size=\"(.*?)"/', $params, $size);

		$shortcode_data = array(
			'id'        => 'title-' . $id[1] . '-sec',
			'font_size' => $size[1],
		);
		$css .= uncode_get_dynamic_css_font_size_shortcode( $shortcode_data );
	}

	$regex_index_5 = '/\[uncode_menu_block ([^\[]*?) icon_accordion_size="(.*?)"(.*?)\]/m';
	preg_match_all( $regex_index_5, $content, $indexes_5, PREG_SET_ORDER, 0 );

	foreach ( $indexes_5 as $index_5 ) {
		$params = $index_5[0];

		preg_match('/ uncode_shortcode_id=\"(.*?)"/', $params, $id); //row ID
		preg_match('/ icon_accordion_size=\"(.*?)"/', $params, $size);

		$shortcode_data = array(
			'id'        => 'icon-' . $id[1],
			'font_size' => $size[1],
		);
		$css .= uncode_get_dynamic_css_font_size_shortcode( $shortcode_data );
	}

	return $css;
}

/**
 * Get CSS from font size shortcode
 */
function uncode_get_dynamic_css_font_size_shortcode( $shortcode_data ) {
	global $uncode_dynamic_css_selectors;

	$css = '';

	if ( isset( $shortcode_data['id'] ) ) {

		$shortcode_id = esc_attr( $shortcode_data['id'] );
		$font_size = $shortcode_data['font_size'];

		// Check if we have already processed the same ID
		// (ie. a cloned module)
		if ( is_array( $uncode_dynamic_css_selectors ) && in_array( 'fontsize-'.$shortcode_id . '-custom', $uncode_dynamic_css_selectors ) ) {
			return $css;
		}

		if ( is_numeric($font_size) ) {
			$font_size .= 'px';
		}
		$numeric_val = str_replace('px', '', $font_size);
		if ( is_numeric($numeric_val) && strpos($font_size, 'px') !== false ) {
			$css .= '.fontsize-' . $shortcode_id . '-custom { font-size: ' . $font_size . '; }';
			$css .= '.menu-container .fontsize-' . $shortcode_id . '-custom a { font-size: ' . $font_size . ' !important; }';
			$first_mquery = $numeric_val / 1.5;
			if ($numeric_val > 35) {
				$css .= '@media (max-width: 959px) { .fontsize-' . $shortcode_id . '-custom { font-size: ' . $first_mquery . 'px; }}';
				if ($first_mquery > 35) {
					$css .= '@media (max-width: 569px) { .fontsize-' . $shortcode_id . '-custom { font-size: 35px; }}';
				}
			}
			if ($first_mquery > 28) {
				$css .= '@media (max-width: 320px) { .fontsize-' . $shortcode_id . '-custom { font-size: 28px; }}';
			}
		} else {
			$css .= '.fontsize-' . $shortcode_id . '-custom { font-size:' . $font_size . ' }';
			$css .= '.menu-container .fontsize-' . $shortcode_id . '-custom a { font-size: ' . $font_size . ' !important; }';
		}

		$uncode_dynamic_css_selectors[] = 'fontsize-'.$shortcode_id . '-custom';
	}

	return $css;
}



/**
 * Get dynamic text indent CSS
 */
function uncode_get_dynamic_css_text_indent( $content_array ) {
	$css = '';

	foreach ( $content_array as $content ) {
		if ( preg_match( '/\[vc_custom_heading[^\]]+text_indent="(.*?)"/', $content ) !== false ) {
			$css .= uncode_get_single_dynamic_css_text_indent( $content );
		}
	}

	return $css;
}

/**
 * Get dynamic text indent CSS from a piece of content
 */
function uncode_get_single_dynamic_css_text_indent( $content ) {
	$css = '';

	$regex_index = '/\[vc_custom_heading[^\]]+text_indent="(.*?)"/m';
	preg_match_all( $regex_index, $content, $indexes, PREG_SET_ORDER, 0 );

	foreach ( $indexes as $index ) {
		$params = $index[0];

		preg_match('/ uncode_shortcode_id=\"(.*?)"/', $params, $id); //row ID
		preg_match('/ text_indent=\"(.*?)"/', $params, $size);

		$shortcode_data = array(
			'id'        => $id[1],
			'text_indent' => $size[1],
		);
		$css .= uncode_get_dynamic_css_text_indent_shortcode( $shortcode_data );
	}

	return $css;
}

/**
 * Get CSS text indent grids shortcode
 */
function uncode_get_dynamic_css_text_indent_shortcode( $shortcode_data ) {
	global $uncode_dynamic_css_selectors;

	$css = '';

	if ( isset( $shortcode_data['id'] ) ) {

		$shortcode_id = absint( $shortcode_data['id'] );
		$text_indent = $shortcode_data['text_indent'];

		// Check if we have already processed the same ID
		// (ie. a cloned module)
		if ( is_array( $uncode_dynamic_css_selectors ) && in_array( 'text-'.$shortcode_id . '-indent', $uncode_dynamic_css_selectors ) ) {
			return $css;
		}

		if ( is_numeric($text_indent) ) {
			$text_indent .= 'px';
		}
		$css .= '@media (min-width: 570px) { ';
		$css .= '.text-' . $shortcode_id . '-indent { text-indent: ' . $text_indent . '; }';
		$css .= '.text-' . $shortcode_id . '-indent .heading-foreword { margin-left: -' . $text_indent . '; margin-right: ' . $text_indent . '; text-indent: 0; width: 0; }';
		$css .= '.text-' . $shortcode_id . '-indent span:not(:first-child) { text-indent: 0; }';
		$css .= ' }';

		$uncode_dynamic_css_selectors[] = 'text-'.$shortcode_id . '-indent:first-child';
	}

	return $css;
}

/**
 * Get dynamic text indent CSS
 */
function uncode_get_dynamic_css_nav_carousel( $content_array ) {
	$css = '';

	foreach ( $content_array as $content ) {
		if ( preg_match( '/\[uncode_carousel_nav[^\]]+[dot_single_width|dot_single_height|dot_single_space|dot_single_radius|dot_single_active|dot_single_boundary|dot_number_align|counter_index_width]="(.*?)"/', $content ) !== false ) {
			$css .= uncode_get_single_dynamic_css_nav_carousel( $content );
		}
	}

	return $css;
}

/**
 * Get dynamic text indent CSS from a piece of content
 */
function uncode_get_single_dynamic_css_nav_carousel( $content ) {
	$css = '';

	$regex_index = '/\[uncode_carousel_nav[^\]]+[dot_single_width|dot_single_height|dot_single_space|dot_single_radius|dot_single_active|dot_single_boundary|dot_number_align|counter_index_width]="(.*?)"/m';
	preg_match_all( $regex_index, $content, $indexes, PREG_SET_ORDER, 0 );

	foreach ( $indexes as $index ) {
		$params = $index[0];

		preg_match('/ uncode_shortcode_id=\"(.*?)"/', $params, $id); //row ID
		preg_match('/ dot_single_width=\"(.*?)"/', $params, $width);
		preg_match('/ dot_single_height=\"(.*?)"/', $params, $height);
		preg_match('/ dot_single_space=\"(.*?)"/', $params, $space);
		preg_match('/ dot_single_radius=\"(.*?)"/', $params, $radius);
		preg_match('/ dot_single_active=\"(.*?)"/', $params, $active);
		preg_match('/ dot_single_boundary=\"(.*?)"/', $params, $boundary);
		preg_match('/ dot_number_align=\"(.*?)"/', $params, $align);
		preg_match('/ counter_index_width=\"(.*?)"/', $params, $counter_w);
		preg_match('/ dots_style=\"(.*?)"/', $params, $style);

		$shortcode_data = array(
			'id'        => $id[1],
			'width' => isset($width[1]) ? $width[1] : '',
			'height' => isset($height[1]) ? $height[1] : '',
			'space' => isset($space[1]) ? $space[1] : '',
			'radius' => isset($radius[1]) ? $radius[1] : '',
			'active' => isset($active[1]) ? $active[1] : '',
			'boundary' => isset($boundary[1]) ? $boundary[1] : '',
			'align' => isset($align[1]) ? $align[1] : '',
			'counter_w' => isset($counter_w[1]) ? $counter_w[1] : '',
			'style' => isset($style[1]) ? $style[1] : '',
		);
		$css .= uncode_get_dynamic_css_nav_carousel_shortcode( $shortcode_data );
	}

	return $css;
}

/**
 * Get CSS text indent grids shortcode
 */
function uncode_get_dynamic_css_nav_carousel_shortcode( $shortcode_data ) {
	global $uncode_dynamic_css_selectors;

	$css = '';

	if ( isset( $shortcode_data['id'] ) ) {

		$shortcode_id = absint( $shortcode_data['id'] );
		$width = isset($shortcode_data['width']) ? $shortcode_data['width'] : '';
		$height = isset($shortcode_data['height']) ? $shortcode_data['height'] : '';
		$space = isset($shortcode_data['space']) ? $shortcode_data['space'] : '';
		$radius = isset($shortcode_data['radius']) ? $shortcode_data['radius'] : '';
		$active = isset($shortcode_data['active']) ? $shortcode_data['active'] : '';
		$boundary = isset($shortcode_data['boundary']) ? $shortcode_data['boundary'] : '';
		$counter_w = isset($shortcode_data['counter_w']) ? $shortcode_data['counter_w'] : '';
		$align = isset($shortcode_data['align']) ? $shortcode_data['align'] : '';
		$style = isset($shortcode_data['style']) ? $shortcode_data['style'] : '';

		// Check if we have already processed the same ID
		// (ie. a cloned module)
		if ( is_array( $uncode_dynamic_css_selectors ) && in_array( 'carousel-nav-'.$shortcode_id . '-custom', $uncode_dynamic_css_selectors ) ) {
			return $css;
		}

		$return = true;

		if ( $width !== '' ) {
			if ( !is_numeric($width) ) {
				$width = floatval($width);
			}
			if ( is_numeric($width) ) {
				$width .= 'px';
				$return = false;
			}
		}

		if ( $height !== '' ) {
			if ( !is_numeric($height) ) {
				$height = floatval($height);
			}
			if ( is_numeric($height) ) {
				$height .= 'px';
				$return = false;
			}
		}

		if ( $space !== '' ) {
			if ( !is_numeric($space) ) {
				$space = floatval($space);
			}
			if ( is_numeric($space) ) {
				$space .= 'px';
				$return = false;
			}
		}

		if ( $radius !== '' ) {
			if ( !is_numeric($radius) ) {
				$radius = floatval($radius);
			}
			if ( is_numeric($radius) ) {
				$radius .= 'px';
				$return = false;
			}
		}

		if ( $boundary !== '' ) {
			if ( !is_numeric($boundary) ) {
				$boundary = floatval($boundary);
			}
			if ( is_numeric($boundary) ) {
				$boundary = ($boundary*2) . 'px';
				$return = false;
			}
		}

		$active_scale = 1;
		if ( $active !== '' ) {
			if ( !is_numeric($active) ) {
				$active = floatval($active);
			}
			if ( is_numeric($active) ) {
				$def_w = $style === '' ? 8 : 20;
				if ( $width !== '' ) {
					$def_w = floatval($width);
				}
				$active_scale = $active / $def_w;
				$active .= 'px';
				$return = false;
			}
		}

		if ( $counter_w !== '' ) {
			if ( !is_numeric($counter_w) ) {
				$counter_w = floatval($counter_w);
			}
			if ( is_numeric($counter_w) ) {
				$counter_w = $counter_w . 'px';
				$return = false;
			}
		}

		if ( $return === false ) {
			//$css .= '@media (min-width: 570px) { ';
			$css_1 = '';
			if ( $width !== '' ) {
				$css_1 .= 'width: ' . $width . '; height: ' . $width . ';';
			}
			if ( $space !== '' ) {
				$css_1 .= 'margin: 0 ' . $space . ';';
			}
			if ( $radius !== '' ) {
				$css_1 .= 'border-radius: ' . $radius . ';';
			}
			if ( $css_1 !== '' ) {
				$css .= '.carousel-nav-' . $shortcode_id . '-custom.dots-default .uncode-nav-dots .uncode-nav-index span { ';
					$css .= $css_1;
				$css .= ' }';
			}

			$css_2 = '';
			if ( $width !== '' ) {
				$css_2 .= 'width: ' . $width . ';';
			}
			if ( $height !== '' ) {
				$css_2 .= 'height: ' . $height . ';';
			}
			if ( $space !== '' ) {
				$css_2 .= 'margin: 0 ' . $space . ';';
			}
			if ( $radius !== '' ) {
				$css_2 .= 'border-radius: ' . $radius . ';';
			}
			if ( $css_2 !== '' ) {
				$css .= '.carousel-nav-' . $shortcode_id . '-custom.dots-lines .uncode-nav-dots .uncode-nav-index span { ';
					$css .= $css_2;
				$css .= ' }';
			}

			$css_3 = '';
			if ( $width !== '' ) {
				$css_3 .= 'min-width: ' . $width . ';';
			}
			if ( $space !== '' ) {
				if ( $align === 'right' ) {
					$css_3 .= 'margin: 0 0 0 ' . $space . ';';
					$css_3 .= 'text-align: right;';
				} elseif ( $align === 'left' ) {
					$css_3 .= 'margin: 0 ' . $space . ' 0 0;';
					$css_3 .= 'text-align: left;';
				} else {
					$css_3 .= 'margin: 0 ' . $space . ';';
					$css_3 .= 'text-align: center;';
				}
			}
			if ( $css_3 !== '' ) {
				$css .= '.carousel-nav-' . $shortcode_id . '-custom.dots-numbers .uncode-nav-dots .uncode-nav-index span { ';
					$css .= $css_3;
				$css .= ' }';
			}

			if ( $active !== '' ) {
				if ( $active_scale !== 1 ) {
					$css .= '.carousel-nav-' . $shortcode_id . '-custom.dots-default .uncode-nav-dots .uncode-nav-index span { ';
						$css .= 'height: ' . $active . ';';
						$css .= 'width: ' . $active . ';';
						$css .= 'transform: scale(' . 1/$active_scale . ');';
					$css .= ' }';
					$css .= '.carousel-nav-' . $shortcode_id . '-custom.dots-default .uncode-nav-dots .uncode-nav-index.active-index span, ';
					$css .= '.carousel-nav-' . $shortcode_id . '-custom.dots-default .uncode-nav-dots .uncode-nav-index:hover span { ';
						$css .= 'transform: scale(1);';
					$css .= ' }';
				}
				$css .= '.carousel-nav-' . $shortcode_id . '-custom.dots-lines .uncode-nav-dots .uncode-nav-index.active-index span { ';
					$css .= 'width: ' . $active . ';';
				$css .= ' }';
			}

			if ( $boundary !== '' ) {
				$css .= '.carousel-nav-' . $shortcode_id . '-custom.dots-look-border:not(.dots-numbers).uncode-owl-nav .uncode-nav-index span:after,';
				$css .= '.carousel-nav-' . $shortcode_id . '-custom.dots-look-shadow:not(.dots-numbers).uncode-owl-nav .uncode-nav-index span:after {';
					$css .= 'width: calc(100% + ' . $boundary . '); height: calc(100% + ' . $boundary . ');';
				$css .= ' }';
			}

			if ( $counter_w !== '' ) {
				$css .= '.carousel-nav-' . $shortcode_id . '-custom .uncode-nav-counter {';
					$css .= 'min-width: ' . $counter_w . ';';
					$css .= 'justify-content: center;';
				$css .= ' }';
			}

			$uncode_dynamic_css_selectors[] = 'carousel-nav-' . $shortcode_id . '-custom';
		} else {
			return $css;
		}
	}

	return $css;
}

/**
 * Get dynamic menu block CSS
 */
function uncode_get_dynamic_css_menu_block( $content_array ) {
	$css = '';

	foreach ( $content_array as $content ) {
		if ( strpos( $content, '[uncode_menu_block ' ) !== false && ( strpos( $content, 'titles_gap=' ) !== false || strpos( $content, 'nested_list_gap=' ) !== false || strpos( $content, 'indent=' ) !== false || strpos( $content, 'titles_top=' ) !== false  || strpos( $content, 'nested_top=' ) !== false || strpos( $content, 'menu_gap=' ) !== false || strpos( $content, 'description_custom_size=' ) !== false || strpos( $content, 'font_icon_size=' ) !== false || strpos( $content, 'media_icon_size=' ) !== false || strpos( $content, 'bg_size=' ) !== false ) ) {
			$css .= uncode_get_single_dynamic_css_menu_block( $content );
		}
	}

	return $css;
}

/**
 * Get dynamic menu block CSS from a piece of content
 */
function uncode_get_single_dynamic_css_menu_block( $content ) {
	$css = '';

	$regex_index = '/\[uncode_menu_block (.*?)\]/m';
	preg_match_all( $regex_index, $content, $indexes, PREG_SET_ORDER, 0 );

	foreach ( $indexes as $index ) {
		$params = $index[0];

		preg_match('/ uncode_shortcode_id=\"(.*?)"/', $params, $id); //row ID
		preg_match('/ menu_gap=\"(.*?)"/', $params, $gap);
		preg_match('/ titles_gap=\"(.*?)"/', $params, $titles_gap);
		preg_match('/ nested_list_gap=\"(.*?)"/', $params, $nested_list_gap);
		preg_match('/ indent=\"(.*?)"/', $params, $indent);
		preg_match('/ titles_top=\"(.*?)"/', $params, $titles_top);
		preg_match('/ nested_top=\"(.*?)"/', $params, $nested_top);
		preg_match('/ description_custom_size=\"(.*?)"/', $params, $desc);
		preg_match('/ font_icon_size=\"(.*?)"/', $params, $icon);
		preg_match('/ media_icon_size=\"(.*?)"/', $params, $media);
		preg_match('/ bg_size=\"(.*?)"/', $params, $bg);
		preg_match('/ bg_size=\"(.*?)"/', $params, $bg);

		$shortcode_data = array(
			'id' => $id[1],
			'menu_gap' => isset($gap[1]) ? $gap[1] : false,
			'titles_gap' => isset($titles_gap[1]) ? $titles_gap[1] : false,
			'nested_list_gap' => isset($nested_list_gap[1]) ? $nested_list_gap[1] : false,
			'indent' => isset($indent[1]) ? $indent[1] : false,
			'titles_top' => isset($titles_top[1]) ? $titles_top[1] : false,
			'nested_top' => isset($nested_top[1]) ? $nested_top[1] : false,
			'desc_size' => isset($desc[1]) ? $desc[1] : false,
			'icon_size' => isset($icon[1]) ? $icon[1] : false,
			'media_size' => isset($media[1]) ? $media[1] : false,
			'bg_size' => isset($bg[1]) ? $bg[1] : false,
		);
		$css .= uncode_get_dynamic_css_menu_block_shortcode( $shortcode_data );
	}

	return $css;
}

/**
 * Get CSS from menu block shortcode
 */
function uncode_get_dynamic_css_menu_block_shortcode( $shortcode_data ) {
	global $uncode_dynamic_css_selectors;

	$css = '';

	if ( isset( $shortcode_data['id'] ) ) {

		$shortcode_id = absint( $shortcode_data['id'] );
		$menu_gap = isset($shortcode_data['menu_gap']) ? $shortcode_data['menu_gap'] : false;
		$titles_gap = isset($shortcode_data['titles_gap']) ? $shortcode_data['titles_gap'] : false;
		$nested_list_gap = isset($shortcode_data['nested_list_gap']) ? $shortcode_data['nested_list_gap'] : false;
		$indent = isset($shortcode_data['indent']) ? $shortcode_data['indent'] : false;
		$titles_top = isset($shortcode_data['titles_top']) ? $shortcode_data['titles_top'] : false;
		$nested_top = isset($shortcode_data['nested_top']) ? $shortcode_data['nested_top'] : false;
		$desc_size = isset($shortcode_data['desc_size']) ? $shortcode_data['desc_size'] : false;
		$icon_size = isset($shortcode_data['icon_size']) ? $shortcode_data['icon_size'] : false;
		$media_size = isset($shortcode_data['media_size']) ? $shortcode_data['media_size'] : false;
		$title_size = isset($shortcode_data['title_size']) ? $shortcode_data['title_size'] : false;
		$bg_size = isset($shortcode_data['bg_size']) ? $shortcode_data['bg_size'] : false;

		// Check if we have already processed the same ID
		// (ie. a cloned module)
		if ( $menu_gap || $titles_gap || $nested_list_gap || $indent || $titles_top || $nested_top || $desc_size ||  $icon_size || $media_size || $title_size || $bg_size ) {
			if ( is_array( $uncode_dynamic_css_selectors ) && in_array( 'menu-block-'.$shortcode_id . '-custom', $uncode_dynamic_css_selectors ) ) {
				return $css;
			}

			if ( $menu_gap !== false && $menu_gap !== '' ) {
				if ( is_numeric($menu_gap) ) {
					$menu_gap .= 'px';
				}
				$css .= '.menu-block-' . $shortcode_id . '-custom, .menu-block-' . $shortcode_id . '-custom ul.sub-menu { row-gap: ' . $menu_gap . ' !important; }';
				$css .= '.menu-block-' . $shortcode_id . '-custom .is-grid, .menu-block-' . $shortcode_id . '-custom li:not(.menu-block-' . $shortcode_id . '-custom > *:first-child) > *:not(.is-grid *):not(ul), .menu-block-' . $shortcode_id . '-custom.is-grid li li { padding-top: ' . $menu_gap . '; }';
			} else {
				$menu_gap = '18px';
			}
			$_nested_gap = $menu_gap;

			if ( $titles_gap !== false && $titles_gap !== '' ) {
				if ( is_numeric($titles_gap) ) {
					$titles_gap .= 'px';
				}
				if ( $titles_top !== false && $titles_top !== '' ) {
					$_titles_top = $titles_top;
					if ( is_numeric($_titles_top) ) {
						$_titles_top .= 'px';
					}
				} else {
					$_titles_top = '0px';
				}
				$_titles_gap = $titles_gap;
				$css .= '.menu-block-' . $shortcode_id . '-custom ul.no-grandchildren { padding-top: ' . $titles_gap . '; }';
				$css .= '.menu-block-' . $shortcode_id . '-custom ul.no-grandchildren:not(.last-one) { padding-bottom: calc(' . $titles_gap . ' + ' . $_titles_top . ' - ' . $menu_gap . '); }';
				$css .= '.menu-block-' . $shortcode_id . '-custom ul.no-grandchildren > li:first-child {
					padding-top: 0;
				}';
				$css .= '.menu-block-' . $shortcode_id . '-custom:not(.first-grid):not(.has-last-ones) { margin-bottom: -' . $titles_gap . '; }';
			} else {
				$_titles_gap = 0;
			}

			if ( $indent !== false && $indent !== '' ) {
				if ( is_numeric($indent) ) {
					$indent .= 'px';
				}

				$padding_indent = 'padding-left';
				if ( is_rtl() ) {
					$padding_indent = 'padding-right';
				}

				$css .= '.menu-block-' . $shortcode_id . '-custom .unmenu-block { ' . $padding_indent . ': ' . $indent . '; }';
			}

			if ( $titles_top !== false && $titles_top !== '' ) {
				if ( is_numeric($titles_top) ) {
					$titles_top .= 'px';
				}
				$css .= '.menu-block-' . $shortcode_id . '-custom.first-grid > li.last-lis, .menu-block-' . $shortcode_id . '-custom.first-grid > li .menu-item-has-children { padding-top: ' . $titles_top . ' !important; }';
				$css .= '.menu-block-' . $shortcode_id . '-custom.first-grid ul.no-grandchildren:not(.last-one) { padding-bottom: calc(' . $_titles_gap . ' - ' . $titles_top . '); }';
				$css .= '.menu-block-' . $shortcode_id . '-custom:not(.first-grid) li:not(.menu > *:first-child) > *:not(.is-grid *):not(ul) { padding-top: ' . $titles_top . ' !important; }';
							
				$_nested_gap = $titles_top;
			}

			if ( $nested_top !== false && $nested_top !== '' ) {
				if ( is_numeric($nested_top) ) {
					$nested_top .= 'px';
				}
				$css .= '.menu-block-' . $shortcode_id . '-custom.first-grid > li li .menu-item-has-children { padding-top: ' . $nested_top . ' !important; }';
				$css .= '.menu-block-' . $shortcode_id . '-custom:not(.first-grid) li li:not(.menu > *:first-child) > *:not(.is-grid *):not(ul) { padding-top: ' . $nested_top . ' !important; }';
			} else {
				$nested_top = '0px';
			}

			if ( $nested_list_gap !== false && $nested_list_gap !== '' ) {
				if ( is_numeric($nested_list_gap) ) {
					$nested_list_gap .= 'px';
				}
				$css .= '.menu-block-' . $shortcode_id . '-custom ul:not(.no-grandchildren) {
					padding-bottom: calc(' . $nested_list_gap . ' + ' . $nested_top . ' - ' . $_nested_gap . '); 
					padding-top: ' . $nested_list_gap . '; 
				}';
			}

			if ( $desc_size !== false && $desc_size !== '' ) {
				if ( is_numeric($desc_size) ) {
					$desc_size .= 'px';
				}
				$css .= '.menu-block-' . $shortcode_id . '-custom .menu-item-description { font-size: ' . $desc_size . ' !important; }';
			}

			if ( $icon_size !== false && $icon_size !== '') {
				if ( is_numeric($icon_size) ) {
					$icon_size .= 'px';
				}
				$css .= '.menu-block-' . $shortcode_id . '-custom .menu-icon:not(.menu-media) { font-size: ' . $icon_size . ' !important; }';

				if ( $media_size === '' ) {
					$media_size = $icon_size;
				} else {
					if ( is_numeric($media_size) ) {
						$media_size .= 'px';
					}
				}

				$css .= '.menu-block-' . $shortcode_id . '-custom .menu-icon.menu-media { width: ' . $media_size . ' !important; }';
				$css .= '.menu-block-' . $shortcode_id . '-custom .menu-icon:before { width: ' . $media_size . ' !important; }';

			}

			if ( $bg_size !== false && $bg_size !== '' ) {
				if ( is_numeric($bg_size) ) {
					$bg_size .= 'px';
				}
				$css .= '.menu-block-' . $shortcode_id . '-custom .fa-stack:not(.menu-media) { 
					height: ' . $bg_size . ' !important; 
					min-width: ' . $bg_size . ' !important; 
					flex-basis: ' . $bg_size . ' !important; 
				}';
			}

			$uncode_dynamic_css_selectors[] = 'menu-block-'.$shortcode_id . '-custom';
		}
	}

	return $css;
}
